exclude: null
grid-search:

  "--config":
    - "qmix"

  lr:
    - 0.0005

  standardise_rewards:
    - True

  use_rnn:
    - False

  target_update_interval_or_tau:
    - 200

  epsilon_anneal_time:
    - 50000

  test_nepisode:
    - 100

  test_interval:
    - 50000

  log_interval:
    - 50000

  save_model_interval:
    - 50000

  save_model:
    - true
  
  task: 
    - 'objetive'

grid-search-groups:
  env0:
    - "--env-config": "sc2"
    - env_args.map_name: 
      - "Multi_task_6m2M" 